### ISSUE TITLE
HTTP Basic Auth broken

### ISSUE THREAD

**Issue by frederichoule** [G4brym/R2-Explorer#60]
Seems like HTTP Basic Auth is broken on all my R2 Explorer instances this morning, in different Cloudflare accounts. Tried updating to last version, but I still have the error.

Error in console:

```
{
    "message": "Request failed with status code 401",
    "name": "AxiosError",
    "stack": "AxiosError: Request failed with status code 401\n    at Ht (https://***/assets/axios.b579625d.js:3:1037)\n    at XMLHttpRequest.E (https://***/assets/axios.b579625d.js:3:4325)",
    "config": {
        "transitional": {
            "silentJSONParsing": true,
            "forcedJSONParsing": true,
            "clarifyTimeoutError": false
        },
        "adapter": [
            "xhr",
            "http"
        ],
        "transformRequest": [
            null
        ],
        "transformResponse": [
            null
        ],
        "timeout": 0,
        "xsrfCookieName": "XSRF-TOKEN",
        "xsrfHeaderName": "X-XSRF-TOKEN",
        "maxContentLength": -1,
        "maxBodyLength": -1,
        "env": {},
        "headers": {
            "Accept": "application/json, text/plain, */*"
        },
        "baseURL": "https://***/api",
        "method": "get",
        "url": "/server/config"
    },
    "code": "ERR_BAD_REQUEST",
    "status": 401
}
```

**Comment by frederichoule** [comment]
Disabling HTTP Basic Auth makes everything work. I am not sure if the problem is from Cloudflare or a recent browser update, but I have the same problem on the latest Chrome and Safari.

**Comment by frederichoule** [comment]
Seems to be fixed!
